### ISSUE TITLE
actions-rs is not maintained

### ISSUE THREAD

**Issue by sksat** [Alignof/rust_template#1]
recommend to use https://github.com/dtolnay/rust-toolchain

example: https://github.com/sksat/rust-template/blob/58cace83a1b70fc1587a2837dcbf7e121bd31277/.github/workflows/rust.yml

**Comment by Alignof** [comment]
Fixed. 
https://github.com/Alignof/rust_template/blob/ce528508a32e56fc0e83146ff46dff2c14f13376/.github/workflows/rust.yml
Thank you mate.
